WIP: Add Cosmos transfer docs
figment-networks/figment-documentation pull request #177
Opened 2022-10-18 14:01 UTC by flanagansteve

need to check about var names VS real examples

2022-10-18 15:11 UTC, pyr0gan commented on docs/guides/staking-api/Cosmos/transfer/2_submit-transfer-data.mdx
> +-H 'Authorization: Bearer YOUR-BEARER-TOKEN' \
@flanagansteve - Correction, a Bearer token is not used:

> -H 'Authorization: <api_key>' \

2022-10-18 15:11 UTC, pyr0gan commented on docs/guides/staking-api/Cosmos/transfer/2_submit-transfer-data.mdx
> +Note that in this step, Slate will check that your account balance is greater than or equal to the amount you've submitted for transfer. Expect an error response if that is not the case.
> Note that in this step, the Staking API will check that your account balance is greater than or equal to the amount you've submitted for transfer. Expect an error response if that is not the case.

2022-10-18 15:12 UTC, pyr0gan commented on docs/guides/staking-api/Cosmos/transfer/4_submit-signed-transaction.mdx
> +- `transfer_tx_broadcasting` &mdash; Transaction has been broadcast and is waiting confirmation.
> ... is waiting for confirmation.

2022-10-18 15:13 UTC, pyr0gan commented on docs/guides/staking-api/Cosmos/transfer/5_get-flow-status.mdx
> +-H 'Authorization: Bearer YOUR-BEARER-TOKEN'
See previous comment: https://github.com/figment-networks/figment-documentation/pull/177/files#r998372457

2022-10-18 15:14 UTC, pyr0gan commented on docs/guides/staking-api/Cosmos/transfer/5_get-flow-status.mdx
> +:::info note
This admonition must be closed:

```text
:::info

sometext

:::
```

2022-10-20 14:50 UTC, pyr0gan approved these changes
Minor fixes, but looks good and should be alright to publish after @CharlesJonesFigment reviews the copy.

2022-10-20 14:50 UTC, pyr0gan commented on docs/guides/staking-api/Cosmos/transfer/1_create-new-flow.mdx
> +title: Create a New Flow
> Create a New Transfer Flow

2022-10-20 14:50 UTC, pyr0gan commented on docs/guides/staking-api/Cosmos/transfer/2_submit-transfer-data.mdx
> +After collecting the required inputs, send a `PUT` request to `/api/v1/flows/[:flow_id]/next` to move on to the next step.
> ... proceed to the next step

2022-10-20 15:05 UTC, pyr0gan commented
@flanagansteve I've made some small fixes, we also like to include the responses from the Staking API. There is one left to capture, it's in the Get Flow Status step (I left a comment there). 👍

2022-10-20 20:24 UTC, CharlesJonesFigment commented on docs/guides/staking-api/Cosmos/transfer/2_submit-transfer-data.mdx
> +  - `from_account_address` &mdash; `string` The address which ATOM will be transferred from (required).
The address from which the ATOM will be transferred (required).

2022-10-20 20:27 UTC, CharlesJonesFigment commented on docs/guides/staking-api/Cosmos/transfer/5_get-flow-status.mdx
> +Congratulations, you have successfully transfered your ATOM tokens!
transferred 
this should have two Rs. it's common throughout the Figment docs.

2022-10-20 20:32 UTC, CharlesJonesFigment requested changes
Hi! I left two comments for you. Very minor.

2022-10-20 21:02 UTC, pyr0gan commented on docs/guides/staking-api/Cosmos/transfer/5_get-flow-status.mdx
> +Congratulations, you have successfully transfered your ATOM tokens!
It's a typo in the responses from the Staking API itself, I believe. Regardless, this instance in the copy should be fixed for sure. I used to use Grammarly in VSCode but I've cancelled my subscription a while back so things like this aren't highlighted and caught immediately.
😄

2022-10-20 21:09 UTC, CharlesJonesFigment approved these changes

2022-10-21 15:51 UTC, pyr0gan commented
- Need sample responses before we can merge and do a final review.

2022-10-25 18:56 UTC, pyr0gan approved these changes

2022-10-25 18:57 UTC, pyr0gan commented
Thanks @flanagansteve 🚀

2022-10-25 18:58 UTC, merged